title: Stefan Crnobrnja
email: stefanc004@gmail.com
description: >- 
  A portfolio website showcasing my CV and projects/En portfolio-webbplats som visar mitt CV och projekt.
baseurl: ""
logo: /assets/img/me.png
fakegpt: /assets/img/fakegptss.png
eshop: /assets/img/eshopss.png
pressice: /assets/img/pressicess.png
schoolmgmt: /assets/img/schoolmanagementss.png
bthpin: /assets/img/BTHpin.png
show_downloads: true
theme: jekyll-theme-cayman